/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AddressBook_JDBC;

import java.sql.*;

public class Library {
	public boolean someLibraryMethod() {
		return true;
	}
}
